remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Russian ⇒ Komi Zyryam
description: An electronic dictionary from Russian to Komi Zyryam
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: minimal
