theme: jekyll-theme-giellalt
title: Dictionary for Russian ⇒ Komi Zyryam
description: An electronic dictionary from Russian to Komi Zyryam

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
